openapi: 3.0.3
info:
  title: Auth API
  version: 1.0.0
  description: API endpoints for authentication and user login via phone/OTP, Google, and Apple.

servers:
  - url: http://localhost:3000/api/v1/auth
    description: Local development server

paths:
  /verify-phone:
    post:
      summary: Send OTP to phone based on request. Different requests are login, signup with phone and change phone number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - phone
                - requestType
              properties:
                phone:
                  type: string
                requestType:
                  type: string
                  enum: [LOGIN, SIGNUP, CHANGE_PHONE, FORGOT_PASSWORD]
      responses:
        '200':
          description: OTP sent successfully

  /verify-request:
    post:
      summary: Verify OTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - phone
                - otp
                - requestType
              properties:
                phone:
                  type: string
                otp:
                  type: string
                requestType:
                  type: string
                  enum: [LOGIN, SIGNUP, CHANGE_PHONE, FORGOT_PASSWORD]
                newPhone:
                  type: string
                fcmToken:
                  type: string
      responses:
        '200':
          description: Verification successful

  /login-attempt:
    post:
      summary: Initiate login by sending OTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - phone
              properties:
                phone:
                  type: string
      responses:
        '200':
          description: OTP sent for login

  /login:
    post:
      summary: Login with OTP or provider
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                otp:
                  type: string
                fcmtoken:
                  type: string
                provider:
                  type: string
                appleId:
                  type: string
      responses:
        '200':
          description: Login successful

  /logout:
    post:
      summary: Logout current user
      responses:
        '200':
          description: Logout successful

  /get-me:
    get:
      summary: Get current user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile data

  /resend-otp:
    post:
      summary: Resend the OTP to a user
      responses:
        '200':
          description: OTP resent

  /google-login:
    get:
      summary: Start Google OAuth login flow
      responses:
        '302':
          description: Redirect to Google login

  /google/callback:
    get:
      summary: Google OAuth callback
      responses:
        '200':
          description: Google login success or redirect

  /apple-login:
    get:
      summary: Start Apple OAuth login flow
      responses:
        '302':
          description: Redirect to Apple login

  /auth/apple/callback:
    post:
      summary: Apple OAuth callback
      responses:
        '200':
          description: Apple login successful

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
